require'glsock2'

-- TODO: Replace the error descriptor with a actual description.
GLSockErrorCodes = 
{
	GLSOCK_ERROR_SUCCESS = "GLSOCK_ERROR_SUCCESS",
	GLSOCK_ERROR_ACCESSDENIED = "GLSOCK_ERROR_ACCESSDENIED",
	GLSOCK_ERROR_ADDRESSFAMILYNOTSUPPORTED = "GLSOCK_ERROR_ADDRESSFAMILYNOTSUPPORTED",
	GLSOCK_ERROR_ADDRESSINUSE = "GLSOCK_ERROR_ADDRESSINUSE",
	GLSOCK_ERROR_ALREADYCONNECTED = "GLSOCK_ERROR_ALREADYCONNECTED",
	GLSOCK_ERROR_ALREADYSTARTED = "GLSOCK_ERROR_ALREADYSTARTED",
	GLSOCK_ERROR_BROKENPIPE = "GLSOCK_ERROR_BROKENPIPE",
	GLSOCK_ERROR_CONNECTIONABORTED = "GLSOCK_ERROR_CONNECTIONABORTED",
	GLSOCK_ERROR_CONNECTIONREFUSED = "GLSOCK_ERROR_CONNECTIONREFUSED",
	GLSOCK_ERROR_CONNECTIONRESET = "GLSOCK_ERROR_CONNECTIONRESET",
	GLSOCK_ERROR_BADDESCRIPTOR = "GLSOCK_ERROR_BADDESCRIPTOR",
	GLSOCK_ERROR_BADADDRESS = "GLSOCK_ERROR_BADADDRESS",
	GLSOCK_ERROR_HOSTUNREACHABLE = "GLSOCK_ERROR_HOSTUNREACHABLE",
	GLSOCK_ERROR_INPROGRESS = "GLSOCK_ERROR_INPROGRESS",
	GLSOCK_ERROR_INTERRUPTED = "GLSOCK_ERROR_INTERRUPTED",
	GLSOCK_ERROR_INVALIDARGUMENT = "GLSOCK_ERROR_INVALIDARGUMENT",
	GLSOCK_ERROR_MESSAGESIZE = "GLSOCK_ERROR_MESSAGESIZE",
	GLSOCK_ERROR_NAMETOOLONG = "GLSOCK_ERROR_NAMETOOLONG",
	GLSOCK_ERROR_NETWORKDOWN = "GLSOCK_ERROR_NETWORKDOWN",
	GLSOCK_ERROR_NETWORKRESET = "GLSOCK_ERROR_NETWORKRESET",
	GLSOCK_ERROR_NETWORKUNREACHABLE = "GLSOCK_ERROR_NETWORKUNREACHABLE",
	GLSOCK_ERROR_NODESCRIPTORS = "GLSOCK_ERROR_NODESCRIPTORS",
	GLSOCK_ERROR_NOBUFFERSPACE = "GLSOCK_ERROR_NOBUFFERSPACE",
	GLSOCK_ERROR_NOMEMORY = "GLSOCK_ERROR_NOMEMORY",
	GLSOCK_ERROR_NOPERMISSION = "GLSOCK_ERROR_NOPERMISSION",
	GLSOCK_ERROR_NOPROTOCOLOPTION = "GLSOCK_ERROR_NOPROTOCOLOPTION",
	GLSOCK_ERROR_NOTCONNECTED = "GLSOCK_ERROR_NOTCONNECTED",
	GLSOCK_ERROR_NOTSOCKET = "GLSOCK_ERROR_NOTSOCKET",
	GLSOCK_ERROR_OPERATIONABORTED = "GLSOCK_ERROR_OPERATIONABORTED",
	GLSOCK_ERROR_OPERATIONNOTSUPPORTED = "GLSOCK_ERROR_OPERATIONNOTSUPPORTED",
	GLSOCK_ERROR_SHUTDOWN = "GLSOCK_ERROR_SHUTDOWN",
	GLSOCK_ERROR_TIMEDOUT = "GLSOCK_ERROR_TIMEDOUT",
	GLSOCK_ERROR_TRYAGAIN = "GLSOCK_ERROR_TRYAGAIN",
	GLSOCK_ERROR_WOULDBLOCK = "GLSOCK_ERROR_WOULDBLOCK"
}

-- TODO: Helper functions maybe?